/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as CguRouteImport } from './routes/cgu'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingStep2RouteImport } from './routes/onboarding/step-2'
import { Route as OnboardingStep1RouteImport } from './routes/onboarding/step-1'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AppNouvelleAnalyseRouteImport } from './routes/app/nouvelle-analyse'
import { Route as AppAnalysesIndexRouteImport } from './routes/app/analyses/index'
import { Route as AppAnalysesIdRouteImport } from './routes/app/analyses/$id'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const CguRoute = CguRouteImport.update({
  id: '/cgu',
  path: '/cgu',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingStep2Route = OnboardingStep2RouteImport.update({
  id: '/onboarding/step-2',
  path: '/onboarding/step-2',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingStep1Route = OnboardingStep1RouteImport.update({
  id: '/onboarding/step-1',
  path: '/onboarding/step-1',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppNouvelleAnalyseRoute = AppNouvelleAnalyseRouteImport.update({
  id: '/app/nouvelle-analyse',
  path: '/app/nouvelle-analyse',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAnalysesIndexRoute = AppAnalysesIndexRouteImport.update({
  id: '/app/analyses/',
  path: '/app/analyses/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAnalysesIdRoute = AppAnalysesIdRouteImport.update({
  id: '/app/analyses/$id',
  path: '/app/analyses/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cgu': typeof CguRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/dashboard': typeof DashboardRoute
  '/app/nouvelle-analyse': typeof AppNouvelleAnalyseRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/onboarding/step-1': typeof OnboardingStep1Route
  '/onboarding/step-2': typeof OnboardingStep2Route
  '/app/analyses/$id': typeof AppAnalysesIdRoute
  '/app/analyses/': typeof AppAnalysesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cgu': typeof CguRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/dashboard': typeof DashboardRoute
  '/app/nouvelle-analyse': typeof AppNouvelleAnalyseRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/onboarding/step-1': typeof OnboardingStep1Route
  '/onboarding/step-2': typeof OnboardingStep2Route
  '/app/analyses/$id': typeof AppAnalysesIdRoute
  '/app/analyses': typeof AppAnalysesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cgu': typeof CguRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/dashboard': typeof DashboardRoute
  '/app/nouvelle-analyse': typeof AppNouvelleAnalyseRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/onboarding/step-1': typeof OnboardingStep1Route
  '/onboarding/step-2': typeof OnboardingStep2Route
  '/app/analyses/$id': typeof AppAnalysesIdRoute
  '/app/analyses/': typeof AppAnalysesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cgu'
    | '/confidentialite'
    | '/dashboard'
    | '/app/nouvelle-analyse'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/signup'
    | '/onboarding/step-1'
    | '/onboarding/step-2'
    | '/app/analyses/$id'
    | '/app/analyses/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cgu'
    | '/confidentialite'
    | '/dashboard'
    | '/app/nouvelle-analyse'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/signup'
    | '/onboarding/step-1'
    | '/onboarding/step-2'
    | '/app/analyses/$id'
    | '/app/analyses'
  id:
    | '__root__'
    | '/'
    | '/cgu'
    | '/confidentialite'
    | '/dashboard'
    | '/app/nouvelle-analyse'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/signup'
    | '/onboarding/step-1'
    | '/onboarding/step-2'
    | '/app/analyses/$id'
    | '/app/analyses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CguRoute: typeof CguRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  DashboardRoute: typeof DashboardRoute
  AppNouvelleAnalyseRoute: typeof AppNouvelleAnalyseRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  OnboardingStep1Route: typeof OnboardingStep1Route
  OnboardingStep2Route: typeof OnboardingStep2Route
  AppAnalysesIdRoute: typeof AppAnalysesIdRoute
  AppAnalysesIndexRoute: typeof AppAnalysesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cgu': {
      id: '/cgu'
      path: '/cgu'
      fullPath: '/cgu'
      preLoaderRoute: typeof CguRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/step-2': {
      id: '/onboarding/step-2'
      path: '/onboarding/step-2'
      fullPath: '/onboarding/step-2'
      preLoaderRoute: typeof OnboardingStep2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/step-1': {
      id: '/onboarding/step-1'
      path: '/onboarding/step-1'
      fullPath: '/onboarding/step-1'
      preLoaderRoute: typeof OnboardingStep1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/nouvelle-analyse': {
      id: '/app/nouvelle-analyse'
      path: '/app/nouvelle-analyse'
      fullPath: '/app/nouvelle-analyse'
      preLoaderRoute: typeof AppNouvelleAnalyseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/analyses/': {
      id: '/app/analyses/'
      path: '/app/analyses'
      fullPath: '/app/analyses/'
      preLoaderRoute: typeof AppAnalysesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/analyses/$id': {
      id: '/app/analyses/$id'
      path: '/app/analyses/$id'
      fullPath: '/app/analyses/$id'
      preLoaderRoute: typeof AppAnalysesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CguRoute: CguRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  DashboardRoute: DashboardRoute,
  AppNouvelleAnalyseRoute: AppNouvelleAnalyseRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  OnboardingStep1Route: OnboardingStep1Route,
  OnboardingStep2Route: OnboardingStep2Route,
  AppAnalysesIdRoute: AppAnalysesIdRoute,
  AppAnalysesIndexRoute: AppAnalysesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
