/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EstimerIndexRouteImport } from './routes/estimer/index'
import { Route as BiensIndexRouteImport } from './routes/biens/index'
import { Route as AnnoncesIndexRouteImport } from './routes/annonces/index'
import { Route as EstimerResultatRouteImport } from './routes/estimer/resultat'
import { Route as EstimerPhotosRouteImport } from './routes/estimer/photos'
import { Route as EstimerLiensComparablesRouteImport } from './routes/estimer/liens-comparables'
import { Route as EstimerDescriptionRouteImport } from './routes/estimer/description'
import { Route as EstimerCompteRouteImport } from './routes/estimer/compte'
import { Route as EstimerCalculRouteImport } from './routes/estimer/calcul'
import { Route as AuthVerifierEmailRouteImport } from './routes/auth/verifier-email'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AnnoncesBienIdRouteImport } from './routes/annonces/$bienId'
import { Route as BiensBienIdIndexRouteImport } from './routes/biens/$bienId/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EstimerIndexRoute = EstimerIndexRouteImport.update({
  id: '/estimer/',
  path: '/estimer/',
  getParentRoute: () => rootRouteImport,
} as any)
const BiensIndexRoute = BiensIndexRouteImport.update({
  id: '/biens/',
  path: '/biens/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnoncesIndexRoute = AnnoncesIndexRouteImport.update({
  id: '/annonces/',
  path: '/annonces/',
  getParentRoute: () => rootRouteImport,
} as any)
const EstimerResultatRoute = EstimerResultatRouteImport.update({
  id: '/estimer/resultat',
  path: '/estimer/resultat',
  getParentRoute: () => rootRouteImport,
} as any)
const EstimerPhotosRoute = EstimerPhotosRouteImport.update({
  id: '/estimer/photos',
  path: '/estimer/photos',
  getParentRoute: () => rootRouteImport,
} as any)
const EstimerLiensComparablesRoute = EstimerLiensComparablesRouteImport.update({
  id: '/estimer/liens-comparables',
  path: '/estimer/liens-comparables',
  getParentRoute: () => rootRouteImport,
} as any)
const EstimerDescriptionRoute = EstimerDescriptionRouteImport.update({
  id: '/estimer/description',
  path: '/estimer/description',
  getParentRoute: () => rootRouteImport,
} as any)
const EstimerCompteRoute = EstimerCompteRouteImport.update({
  id: '/estimer/compte',
  path: '/estimer/compte',
  getParentRoute: () => rootRouteImport,
} as any)
const EstimerCalculRoute = EstimerCalculRouteImport.update({
  id: '/estimer/calcul',
  path: '/estimer/calcul',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifierEmailRoute = AuthVerifierEmailRouteImport.update({
  id: '/auth/verifier-email',
  path: '/auth/verifier-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnoncesBienIdRoute = AnnoncesBienIdRouteImport.update({
  id: '/annonces/$bienId',
  path: '/annonces/$bienId',
  getParentRoute: () => rootRouteImport,
} as any)
const BiensBienIdIndexRoute = BiensBienIdIndexRouteImport.update({
  id: '/biens/$bienId/',
  path: '/biens/$bienId/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/annonces/$bienId': typeof AnnoncesBienIdRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verifier-email': typeof AuthVerifierEmailRoute
  '/estimer/calcul': typeof EstimerCalculRoute
  '/estimer/compte': typeof EstimerCompteRoute
  '/estimer/description': typeof EstimerDescriptionRoute
  '/estimer/liens-comparables': typeof EstimerLiensComparablesRoute
  '/estimer/photos': typeof EstimerPhotosRoute
  '/estimer/resultat': typeof EstimerResultatRoute
  '/annonces/': typeof AnnoncesIndexRoute
  '/biens/': typeof BiensIndexRoute
  '/estimer/': typeof EstimerIndexRoute
  '/biens/$bienId/': typeof BiensBienIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/annonces/$bienId': typeof AnnoncesBienIdRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verifier-email': typeof AuthVerifierEmailRoute
  '/estimer/calcul': typeof EstimerCalculRoute
  '/estimer/compte': typeof EstimerCompteRoute
  '/estimer/description': typeof EstimerDescriptionRoute
  '/estimer/liens-comparables': typeof EstimerLiensComparablesRoute
  '/estimer/photos': typeof EstimerPhotosRoute
  '/estimer/resultat': typeof EstimerResultatRoute
  '/annonces': typeof AnnoncesIndexRoute
  '/biens': typeof BiensIndexRoute
  '/estimer': typeof EstimerIndexRoute
  '/biens/$bienId': typeof BiensBienIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/annonces/$bienId': typeof AnnoncesBienIdRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verifier-email': typeof AuthVerifierEmailRoute
  '/estimer/calcul': typeof EstimerCalculRoute
  '/estimer/compte': typeof EstimerCompteRoute
  '/estimer/description': typeof EstimerDescriptionRoute
  '/estimer/liens-comparables': typeof EstimerLiensComparablesRoute
  '/estimer/photos': typeof EstimerPhotosRoute
  '/estimer/resultat': typeof EstimerResultatRoute
  '/annonces/': typeof AnnoncesIndexRoute
  '/biens/': typeof BiensIndexRoute
  '/estimer/': typeof EstimerIndexRoute
  '/biens/$bienId/': typeof BiensBienIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/annonces/$bienId'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/signup'
    | '/auth/verifier-email'
    | '/estimer/calcul'
    | '/estimer/compte'
    | '/estimer/description'
    | '/estimer/liens-comparables'
    | '/estimer/photos'
    | '/estimer/resultat'
    | '/annonces/'
    | '/biens/'
    | '/estimer/'
    | '/biens/$bienId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/annonces/$bienId'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/signup'
    | '/auth/verifier-email'
    | '/estimer/calcul'
    | '/estimer/compte'
    | '/estimer/description'
    | '/estimer/liens-comparables'
    | '/estimer/photos'
    | '/estimer/resultat'
    | '/annonces'
    | '/biens'
    | '/estimer'
    | '/biens/$bienId'
  id:
    | '__root__'
    | '/'
    | '/annonces/$bienId'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/signup'
    | '/auth/verifier-email'
    | '/estimer/calcul'
    | '/estimer/compte'
    | '/estimer/description'
    | '/estimer/liens-comparables'
    | '/estimer/photos'
    | '/estimer/resultat'
    | '/annonces/'
    | '/biens/'
    | '/estimer/'
    | '/biens/$bienId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnnoncesBienIdRoute: typeof AnnoncesBienIdRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthVerifierEmailRoute: typeof AuthVerifierEmailRoute
  EstimerCalculRoute: typeof EstimerCalculRoute
  EstimerCompteRoute: typeof EstimerCompteRoute
  EstimerDescriptionRoute: typeof EstimerDescriptionRoute
  EstimerLiensComparablesRoute: typeof EstimerLiensComparablesRoute
  EstimerPhotosRoute: typeof EstimerPhotosRoute
  EstimerResultatRoute: typeof EstimerResultatRoute
  AnnoncesIndexRoute: typeof AnnoncesIndexRoute
  BiensIndexRoute: typeof BiensIndexRoute
  EstimerIndexRoute: typeof EstimerIndexRoute
  BiensBienIdIndexRoute: typeof BiensBienIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estimer/': {
      id: '/estimer/'
      path: '/estimer'
      fullPath: '/estimer/'
      preLoaderRoute: typeof EstimerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biens/': {
      id: '/biens/'
      path: '/biens'
      fullPath: '/biens/'
      preLoaderRoute: typeof BiensIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/annonces/': {
      id: '/annonces/'
      path: '/annonces'
      fullPath: '/annonces/'
      preLoaderRoute: typeof AnnoncesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estimer/resultat': {
      id: '/estimer/resultat'
      path: '/estimer/resultat'
      fullPath: '/estimer/resultat'
      preLoaderRoute: typeof EstimerResultatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estimer/photos': {
      id: '/estimer/photos'
      path: '/estimer/photos'
      fullPath: '/estimer/photos'
      preLoaderRoute: typeof EstimerPhotosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estimer/liens-comparables': {
      id: '/estimer/liens-comparables'
      path: '/estimer/liens-comparables'
      fullPath: '/estimer/liens-comparables'
      preLoaderRoute: typeof EstimerLiensComparablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estimer/description': {
      id: '/estimer/description'
      path: '/estimer/description'
      fullPath: '/estimer/description'
      preLoaderRoute: typeof EstimerDescriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estimer/compte': {
      id: '/estimer/compte'
      path: '/estimer/compte'
      fullPath: '/estimer/compte'
      preLoaderRoute: typeof EstimerCompteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estimer/calcul': {
      id: '/estimer/calcul'
      path: '/estimer/calcul'
      fullPath: '/estimer/calcul'
      preLoaderRoute: typeof EstimerCalculRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verifier-email': {
      id: '/auth/verifier-email'
      path: '/auth/verifier-email'
      fullPath: '/auth/verifier-email'
      preLoaderRoute: typeof AuthVerifierEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/annonces/$bienId': {
      id: '/annonces/$bienId'
      path: '/annonces/$bienId'
      fullPath: '/annonces/$bienId'
      preLoaderRoute: typeof AnnoncesBienIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biens/$bienId/': {
      id: '/biens/$bienId/'
      path: '/biens/$bienId'
      fullPath: '/biens/$bienId/'
      preLoaderRoute: typeof BiensBienIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnnoncesBienIdRoute: AnnoncesBienIdRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthVerifierEmailRoute: AuthVerifierEmailRoute,
  EstimerCalculRoute: EstimerCalculRoute,
  EstimerCompteRoute: EstimerCompteRoute,
  EstimerDescriptionRoute: EstimerDescriptionRoute,
  EstimerLiensComparablesRoute: EstimerLiensComparablesRoute,
  EstimerPhotosRoute: EstimerPhotosRoute,
  EstimerResultatRoute: EstimerResultatRoute,
  AnnoncesIndexRoute: AnnoncesIndexRoute,
  BiensIndexRoute: BiensIndexRoute,
  EstimerIndexRoute: EstimerIndexRoute,
  BiensBienIdIndexRoute: BiensBienIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
